
# Site settings
title: Apache Guacamole

# Build settings
markdown: kramdown

# Custom collections
collections:

    # All Apache Guacamole releases
    releases:
        output: true
        permalink: /release/release-notes-:title

    # Pseudo-pages describing direct links to other pages (possibly external)
    links:
        output: false

# Site-wide defaults
defaults:

    # All releases should use the "release" layout
    - scope:  { type: releases }
      values: { layout: release }

